name: egoexoems
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py38h578d9bd_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py38h5eee18b_0
  - pip=23.3.1=py38h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - ace-tools==0.0
      - addict==2.4.0
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - audioread==3.0.1
      - autodistill==0.1.28
      - autodistill-grounding-dino==0.1.4
      - av==12.0.0
      - cachetools==5.3.3
      - cffi==1.17.1
      - click==8.1.7
      - coco-eval==0.0.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - dacite==1.8.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - fasttext==0.9.2
      - filetype==1.2.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gensim==4.3.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.1
      - htmlmin==0.1.12
      - huggingface-hub==0.24.5
      - idna==3.7
      - imagehash==4.3.1
      - imageio==2.34.2
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipywidgets==8.1.3
      - jax==0.4.13
      - jaxlib==0.4.13
      - joblib==1.4.0
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - libyana==0.0.1
      - lightning-utilities==0.11.6
      - llvmlite==0.41.1
      - lmdb==1.4.1
      - markdown==3.6
      - matplotlib==3.7.5
      - mediapipe==0.10.11
      - ml-dtypes==0.2.0
      - msgpack==1.1.0
      - multidict==6.0.5
      - multimethod==1.10
      - numba==0.58.1
      - numpy==1.23.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - pandas==2.0.3
      - pandas-profiling==3.6.6
      - patsy==0.5.6
      - phik==0.12.4
      - plotly==5.24.1
      - pooch==1.8.2
      - prefetch-generator==1.0.3
      - protobuf==3.20.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pybind11==2.12.0
      - pycocotools==2.0.7
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pywavelets==1.4.1
      - regex==2024.7.24
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rf-groundingdino==0.1.2
      - rf-segment-anything==1.0
      - roboflow==1.1.47
      - rsa==4.9
      - safetensors==0.4.4
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - seaborn==0.13.2
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smart-open==7.0.4
      - smmap==5.0.1
      - sounddevice==0.5.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - statsmodels==0.14.1
      - supervision==0.24.0
      - tenacity==9.0.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - tifffile==2023.7.10
      - timm==1.0.9
      - tokenizers==0.19.1
      - tomli==2.0.2
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchmetrics==1.4.1
      - torchvision==0.19.1
      - tqdm==4.66.2
      - transformers==4.44.0
      - triton==3.0.0
      - typeguard==4.3.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.1
      - visions==0.7.6
      - wandb==0.16.6
      - werkzeug==3.0.2
      - widgetsnbextension==4.0.11
      - wordcloud==1.9.3
      - wrapt==1.16.0
      - yapf==0.40.2
      - yarl==1.9.4
      - ydata-profiling==4.9.0
      - zipp==3.18.1
prefix: /scratch/anonymous/conda/egoexoems
